apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea

resources:
  - namespace.yaml
  - secrets.yaml
  - oauthclient.yaml
  - orgs.yaml
  - teams.yaml

helmCharts:
  - name: gitea
    releaseName: gitea
    namespace: gitea
    version: 8.3.0
    repo: https://dl.gitea.io/charts/
    valuesFile: values.yaml
