global:
  storageClass: longhorn

strategy:
  type: Recreate

gitea:
  config:
    cache:
      HOST: memcached:11211
      ADAPTED: memcache
    session:
      PROVIDER_CONFIG: memcache://memcached:11211
      PROVIDER: memcache
    database:
      DB_TYPE: postgres
      HOST: postgresql
      NAME: gitea
      USER: gitea
      PASSWD: gitea
      SCHEMA: public
    server:
      DOMAIN: gitea.training.cluster.acend.ch
  admin:
    existingSecret: gitea-admin-credentials
    
ingress:
  apiVersion: networking.k8s.io/v1
  enabled: true
  className: haproxy
  hosts:
  - host: gitea.training.cluster.acend.ch
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - gitea.training.cluster.acend.ch
    secretName: acend-wildcard

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false