global:
  storageClass: longhorn


gitea:
  config:
    cache:
      HOST: memcache://memcache:11211
      ADAPTED: memcache
    session:
      HOST: memcache://memcache:11211
      ADAPTED: memcache
    queue:
      HOST: memcache://memcache:11211
      ADAPTED: memcache
    database:
      DB_TYPE: postgresql
      HOST: postgresql
      NAME: gitea
      USER: gitea
      PASSWD: gitea
      SCHEMA: gitea
    server:
      DOMAIN: gitea.training.cluster.acend.ch
  admin:
    existingSecret: gitea-admin-credentials
    
ingress:
  apiVersion: networking.k8s.io/v1
  enabled: true
  className: haproxy
  hosts:
  - host: gitea.training.cluster.acend.ch
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - gitea.training.cluster.acend.ch
    secretName: acend-wildcard

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false