configs:
  rbac: 
    policy.csv: |
      p, role:student, applications, *, */*, allow

      p, role:student, applications, *, infra/*, deny
      p, role:student, applications, *, trainee-environment/*, deny

      p, role:student, clusters, get, *, allow
      p, role:student, clusters, update, *, allow
      p, role:student, repositories, get, *, allow
      p, role:student, repositories, create, *, allow
      p, role:student, repositories, update, *, allow
      p, role:student, repositories, delete, *, allow

      p, role:student, projects, get, *, allow
      p, role:student, projects, create, *, allow
      p, role:student, projects, update, *, allow
      p, role:student, projects, delete, *, allow

      p, role:student, projects, *, infra, deny
      p, role:student, projects, *, trainee-environment, deny

      g, acend:trainees, role:student

      %{~ for i in range(count-students) ~}
      g, ${studentname-prefix}${i+1}, role:student
      %{~ endfor ~}

      g, acend:admins, role:admin
