global:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"

controller:
  metrics:
    enabled: true

configs:
  cm:
    create: true
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - kinds:
        - "CiliumIdentity"
        - "ciliumidentities"
        - "CiliumEndpoint"
        - "ciliumendpoints"
        - "CiliumNode"
        - "ciliumnodes"
    dex.config: |
      connectors:
        - type: gitea
          id: gitea
          name: Gitea
          config:
            clientID: $gitea-oauthclient-argocd:client_id
            clientSecret: $gitea-oauthclient-argocd:client_secret
            redirectURI: https://argocd.${cluster_name}.${cluster_domain}/api/dex/callback
            baseURL: https://gitea.${cluster_name}.${cluster_domain}
            loadAllGroups: true
  params:
    server.insecure: true
    application.namespaces: user*

server:
  ingress:
    enabled: true
    ingressClassName: haproxy
    extraTls:
    - secretName: acend-wildcard
  ingressGrpc:
    enabled: true
    ingressClassName: haproxy
    extraTls:
    - secretName: acend-wildcard