server:
  config:
    %{~ for i in range(count-students) ~}
    accounts.${studentname-prefix}${i+1}: "apiKey, login"
    %{~ endfor ~}

configs:
  secret:
    extra:
      %{~ for i in range(count-students) ~}
      accounts.${studentname-prefix}${i+1}.password: "${passwords[i].bcrypt_hash)}"
      accounts.${studentname-prefix}${i+1}.passwordMtime: "${timestamp()}"
      %{~ endfor ~}
