controller:
  metrics:
    enabled: true

configs:
  params:
    server.insecure: true

server:
  config:
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - kinds:
        - "CiliumIdentity"
        - "ciliumidentities"
        - "CiliumEndpoint"
        - "ciliumendpoints"
        - "CiliumNode"
        - "ciliumnodes"
  ingress:
    enabled: true
    tls:
    - secretName: acend-wildcard
  ingressGrpc:
    enabled: true
    tls:
    - secretName: acend-wildcard