applicationsets:
- name: trainee-env
  namespace: argocd
  generators:
  - list:
      elements:
      %{~ for i in range(count-students) ~}
      - traineename: ${studentname-prefix}${i+1}
        password: "${passwords[i].result}"
        cluster_admin: ${contains(cluster_admin, join("", tolist([studentname-prefix,i+1])))}
      %{~ endfor ~}
  template:
    metadata:
      name: '{{traineename}}-env'
    spec:
      project: trainee-environment
      source:
        repoURL: https://github.com/acend/terraform-k8s-cluster-lab
        targetRevision: HEAD
        path: 'charts/user-env'
        helm:
          releaseName: '{{traineename}}-env'
          values: |
            user: {{traineename}}
            password: {{password}}
            cluster_name: ${cluster_domain}
            cluster_domain: ${cluster_domain}
            cluster_admin: {{cluster_admin}}
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true