apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base


patches:
- patch: |-
    - op: replace
      path: /spec/source/path
      value: deploy/gitea/overlays/test.cluster.acend.ch
  target:
    kind: Application
    name: gitea
- patch: |-
    - op: replace
      path: /spec/source/path
      value: deploy/cert-manager/overlays/test.cluster.acend.ch
  target:
    kind: Application
    name: cert-manager
- patch: |-
    - op: replace
      path: /spec/source/path
      value: deploy/haproxy-ingress/overlays/test.cluster.acend.ch
  target:
    kind: Application
    name: haproxy-ingress
- patch: |-
    - op: replace
      path: /spec/source/path
      value: deploy/welcome/overlays/test.cluster.acend.ch
  target:
    kind: Application
    name: welcome
- patch: |-
    - op: replace
      path: /spec/source/path
      value: deploy/oauth-proxy/overlays/test.cluster.acend.ch
  target:
    kind: Application
    name: oauth-proxy