apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base


patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: welcome.test.cluster.acend.ch
    - op: replace
      path: /spec/tls/0/hosts/0
      value: welcome.test.cluster.acend.ch
  target:
    kind: Ingress
    name: welcome
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: test
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: cluster.acend.ch
  target:
    kind: Deployment
    name: welcome
