#cloud-config

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl; install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube; mv minikube /usr/local/bin

mounts:
- [ bpffs, /sys/fs/bpf, bpf, "default", 0, 0 ]

package_update: true
package_upgrade: true



users:
  - name: ${username}
    groups: docker
    ssh_authorized_keys:
    - ${sshkey}

