#cloud-config

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh
  - curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl; install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube; mv minikube /usr/local/bin
  - curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - iptables -I DOCKER-USER -j ACCEPT
  - echo 'source <(kubectl completion bash)' >> /home/${username}/.bashrc
  - git clone https://github.com/jonmosco/kube-ps1.git /home/${username}/kube-ps1
  - echo 'source /home/${username}/kube-ps1/kube-ps1.sh' >> /home/${username}/.bashrc
  - echo 'PS1='[\u@\h \W $(kube_ps1)]\$ '' >> /home/${username}/.bashrc
  - git clone https://github.com/ahmetb/kubectx /opt/kubectx
  - ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx && ln -s /opt/kubectx/kubens /usr/local/bin/kubens
  - COMPDIR=$(pkg-config --variable=completionsdir bash-completion) && ln -sf /opt/kubectx/completion/kubens.bash $COMPDIR/kubens && ln -sf /opt/kubectx/completion/kubectx.bash $COMPDIR/kubectx



mounts:
- [ bpffs, /sys/fs/bpf, bpf, "default", 0, 0 ]

package_update: true
package_upgrade: true

packages: ['jq']


users:
  - name: ${username}
    groups: docker, admin
    ssh_authorized_keys:
    - ${sshkey}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL


