server:
  rbacConfig: 
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow

      %{~ for i in range(count-students) ~}
      g, student${i+1}, role:org-admin
      %{~ endfor ~}
