---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acend-wildcard
  namespace: cert-manager
spec:
  secretName: acend-wildcard
  dnsNames:
  - "*.training.cluster.acend.ch"
  issuerRef:
    name: letsencrypt-prod-acend
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: certificate-wildcard=true