---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-credentials
  namespace: gitea
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Z2l0ZWFfYWRtaW4=