global:
  storageClass: longhorn

strategy:
  type: Recreate

gitea:
  config:
    server:
      DOMAIN: gitea.test.cluster.acend.ch
  admin:
    existingSecret: gitea-admin-credentials
    
ingress:
  apiVersion: networking.k8s.io/v1
  enabled: true
  className: haproxy
  hosts:
  - host: gitea.test.cluster.acend.ch
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - gitea.test.cluster.acend.ch
    secretName: acend-wildcard

# postgresql-ha:
#   persistence:
#     size: 1Gi

# redis-cluster:
#   persistence:
#     size: 1Gi