---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - namespace.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.0/kubevirt-cr.yaml

patches:
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/useEmulation
      value: true
  target:
    kind: KubeVirt
    name: kubevirt
