---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - namespace.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.3.0/kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.59.0/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.59.0/cdi-cr.yaml

patches:
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/useEmulation
      value: true
  target:
    kind: KubeVirt
    name: kubevirt
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/featureGates/-
      value: Sidecar
  target:
    kind: KubeVirt
    name: kubevirt
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/featureGates/-
      value: CommonInstancetypesDeploymentGate
  target:
    kind: KubeVirt
    name: kubevirt
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/featureGates/-
      value: ExperimentalIgnitionSupport
  target:
    kind: KubeVirt
    name: kubevirt
- patch: |-
    - op: add
      path: /spec/configuration/developerConfiguration/featureGates/-
      value: HotplugVolumes
  target:
    kind: KubeVirt
    name: kubevirt
                       
                   
               
           
