global:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 10m
    memory: 42Mi

webhook:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi