---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgiteateammembers.acend.ch
spec:
  group: acend.ch
  names:
    kind: XGiteaTeamMember
    plural: xgiteateammembers
  claimNames:
    kind: GiteaTeamMember
    plural: giteateammembers
  defaultCompositionRef:
    name: giteateamember
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  team:
                    type: string
                  org:
                    type: string
                  username:
                    type: string
                required:
                - team
                - org
                - username
            required:
              - parameters
          status:
            description: A Status represents the observed state
            properties:
              team_id:
                type: string
                x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: giteateamember
  labels:
    crossplane.io/xrd: xgiteateammembers.acend.ch
spec:
  compositeTypeRef:
    apiVersion: acend.ch/v1alpha1
    kind: XGiteaTeamMember
  resources:
  - name: k8s-giteateam
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        managementPolicy: Observe
        forProvider:
          manifest:
            apiVersion: acend.ch/v1alpha1
            kind: GiteaTeam
            metadata:
              namespace: gitea
        providerConfigRef:
          name: default
    patches:
      - type: CombineFromComposite
        combine:
          variables:
          - fromFieldPath: spec.parameters.org
          - fromFieldPath: spec.parameters.team
          strategy: string
          string:
            fmt: "%s-%s"
        toFieldPath: "spec.forProvider.manifest.metadata.name"
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.manifest.status.id
        toFieldPath: status.team_id
  - name: tf_gitea_team_member
    base:
      apiVersion: tf.upbound.io/v1beta1
      kind: Workspace
      spec:
        providerConfigRef:
          name: gitea
        forProvider:
          source: Inline
          module: |
            terraform {
              required_providers {
                restapi = {
                  source = "Mastercard/restapi"
                }
              }
            }

            variable "team_id" {
              type = string
            }

            variable "user" {
              type = string
            }

            resource "restapi_object" "teamMember" {

              path           = "/api/v1/teams/${var.team_id}/members/${var.user}"
              object_id      = "${var.team_id}-${var.user}"
              update_method  = "PUT"
              create_method  = "PUT"
              update_method  = "PUT"
              destroy_method = "DELETE"
              data           = "{}"
            }


          vars:
            - key: team_id
            - key: user
    patches:
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        transforms:
        - type: string
          string:
            fmt: "giteateammember-%s"
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.name"
        transforms:
        - type: string
          string:
            fmt: "giteateammember-%s"
      - fromFieldPath: status.team_id
        toFieldPath: spec.forProvider.vars[0].value
        policy:
            fromFieldPath: Required
      - fromFieldPath: spec.parameters.username
        toFieldPath: spec.forProvider.vars[1].value
