---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgitearepos.acend.ch
spec:
  group: acend.ch
  names:
    kind: XGiteaRepo
    plural: xgitearepos
  claimNames:
    kind: GiteaRepo
    plural: gitearepos
  defaultCompositionRef:
    name: gitearepo
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  reponame:
                    type: string
                  repourl:
                    type: string
 
                required:
                - reponame
                - repourl
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: xgitearepos.acend.ch
  name: gitearepo
spec:
  compositeTypeRef:
    apiVersion: acend.ch/v1alpha1
    kind: XGiteaRepo
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: tf.upbound.io/v1beta1
          kind: Workspace
          spec:
            forProvider:
              module: |
                terraform {
                  required_providers {
                    restapi = {
                      source = "Mastercard/restapi"
                    }
                  }
                }

                variable "owner" {
                  type = string
                }

                variable "reponame" {
                  type = string
                }

                variable "repourl" {
                  type = string
                }


                resource "restapi_object" "gitea-repo" {

                  path        = "/api/v1/repos"
                  create_path = "/api/v1/repos/migrate"

                  data = (jsonencode({
                    clone_addr = var.repourl
                    private    = false
                    repo_name  = var.reponame
                    repo_owner = var.owner

                  }))
                  id_attribute = "full_name"
                }

                output "repo-original-url" {
                  value = restapi_object.gitea-repo.api_data.original_url
                }

                output "repo-html_url" {
                  value = restapi_object.gitea-repo.api_data.html_url
                }

                output "repo-clone_url" {
                  value = restapi_object.gitea-repo.api_data.clone_url
                }
              source: Inline
              vars:
              - key: owner
              - key: reponame
              - key: repourl
            providerConfigRef:
              name: gitea
        name: tf_gitearepo
        patches:
        - combine:
            strategy: string
            string:
              fmt: gitearepo-%s-%s
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            - fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: CombineFromComposite
        - combine:
            strategy: string
            string:
              fmt: gitearepo-%s-%s
            variables:
            - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            - fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: metadata.name
          type: CombineFromComposite
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.forProvider.vars[0].value
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.reponame
          toFieldPath: spec.forProvider.vars[1].value
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.repourl
          toFieldPath: spec.forProvider.vars[2].value
          type: FromCompositeFieldPath
    step: patch-and-transform
