---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgiteaoauthclients.acend.ch
spec:
  group: acend.ch
  names:
    kind: XGiteaOauthClient
    plural: xgiteaoauthclients
  claimNames:
    kind: GiteaOauthClient
    plural: giteaoauthclients
  defaultCompositionRef:
    name: giteaoauthclient
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                  redirect_uri:
                    type: string
                  secret_namespace:
                    type: string
                  secret_labels:
                    type: object
                required:
                - name
                - redirect_uri
                - secret_namespace
            required:
              - parameters
          status:
            description: A Status represents the observed state
            properties:
              ipv4:
                type: client_id
                x-kubernetes-preserve-unknown-fields: true
              ipv6:
                type: client_secret
                x-kubernetes-preserve-unknown-fields: true
            type: object
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: giteaoauthclient
  labels:
    crossplane.io/xrd: xgiteaoauthclients.acend.ch
spec:
  compositeTypeRef:
    apiVersion: acend.ch/v1alpha1
    kind: XGiteaOauthClient
  resources:
  - name: tf_gitea_oauthclient
    base:
      apiVersion: tf.upbound.io/v1beta1
      kind: Workspace
      spec:
        providerConfigRef:
          name: gitea
        forProvider:
          source: Inline
          module: |
            terraform {
              required_providers {
                restapi = {
                  source = "Mastercard/restapi"
                }
                static = {
                  source  = "tiwood/static"
                }
              }
            }

            variable "name" {
              type = string
            }

            variable "redirect_uri" {
              type = string
            }

            resource "restapi_object" "gitea-oauthclient" {

              path = "/api/v1/user/applications/oauth2"

              data = (jsonencode({
                name                = var.name
                redirect_uris       = [var.redirect_uri]
                confidential_client = true

              }))
              id_attribute = "id"
            }

            resource "static_data" "client_secret" {
              data = {
                client_secret = restapi_object.gitea-oauthclient.api_data.client_secret
              }

              lifecycle {
                ignore_changes = [data]
              }
            }

            output "name" {
              value = restapi_object.gitea-oauthclient.api_data.name
            }

            output "client_id" {
              value = restapi_object.gitea-oauthclient.api_data.client_id
            }

            output "client_secret" {
              value = static_data.client_secret.output.client_secret
            }
          vars:
            - key: name
            - key: redirect_uri
    patches:
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        transforms:
        - type: string
          string:
            fmt: "oauthclient-%s"
      - fromFieldPath: spec.parameters.name
        toFieldPath: spec.forProvider.vars[0].value
      - fromFieldPath: spec.parameters.redirect_uri
        toFieldPath: spec.forProvider.vars[1].value
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.outputs.client_id
        toFieldPath: status.client_id
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.outputs.client_secret
        toFieldPath: status.client_secret
  - name: secret
    base: 
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
        providerConfigRef:
          name: default
    patches:
      - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
        toFieldPath: "metadata.name"
        transforms:
        - type: string
          string:
            fmt: "gitea-oauthclient-%s"
      - fromFieldPath: spec.parameters.secret_namespace
        toFieldPath: metadata.namespace
      - fromFieldPath: spec.parameters.secret_labels
        toFieldPath: metadata.labels
      - fromFieldPath: status.client_id
        toFieldPath: data.client_id
        transforms:
        - type: string
          string:
            type: Convert
            convert: ToBase64
      - fromFieldPath: status.client_secret
        toFieldPath: data.client_secret
        transforms:
        - type: string
          string:
            type: Convert
            convert: ToBase64