---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: trainee-environment
  namespace: argocd
spec:
  description: Project with all apps for the trainee environments
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist:
    - group: '*'
      kind: 'XGiteaUser*'
    - group: '*'
      kind: 'XGiteaTeamMember*'