nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Equal
  value: "true"
  effect: "NoSchedule"

rbacManager:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"