apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: '*.test.cluster.acend.ch'
  target:
    kind: Certificate
    name: acend-wildcard
