---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hosttech-secret-{{ .Values.cluster }}
  namespace: cert-manager
spec:
  refreshInterval: 10s
  deletionPolicy: Delete
  secretStoreRefs:
    - name: cluster-{{ .Values.cluster }}-cert-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: hosttech-secret
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: hosttech-secret
          property: token