---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: hetzner-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: deploy/kubernetes
    repoURL: https://github.com/hetznercloud/csi-driver.git
    targetRevision: v2.3.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true