apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base


patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: oauth-proxy.test.cluster.acend.ch
    - op: replace
      path: /spec/tls/0/hosts/0
      value: oauth-proxy.test.cluster.acend.ch
  target:
    kind: Ingress
    name: oauth2-proxy

