apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    version: 7.7.14
    repo: https://oauth2-proxy.github.io/manifests
    valuesFile: values.yaml


patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/key
      value: client_id
    - op: replace
      path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/key
      value: client_secret
  target:
    kind: Deployment
    name: oauth2-proxy

