apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    version: 6.16.1
    repo: https://oauth2-proxy.github.io/manifests
    valuesFile: values.yaml