config:
  existingSecret: gitea-oauthclient-oauthproxy
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    provider = oidc
    provider-display-name = "Acend Login"

ingress:
 enabled: true
 hosts:
   - oauth-proxy.training.cluster.acend.ch
 tls:
 - hosts:
   - oauth-proxy.training.cluster.acend.ch