config:
  existingSecret: gitea-oauthclient-oauthproxy

extraArgs:
  provider: oidc
  provider-display-name: Acend Login
  oidc-issuer-url: https://gitea.training.cluster.acend.ch/
  custom-sign-in-logo: https://raw.githubusercontent.com/acend/.github/main/profile/images/AC-logo-claim-rgb-red.svg
  whitelist-domain: "*.acend.ch,localhost:*"
  cookie-domain: "acend.ch"

ingress:
 enabled: true
 className: haproxy
 hosts:
   - oauth-proxy.training.cluster.acend.ch
 tls:
 - hosts:
   - oauth-proxy.training.cluster.acend.ch