config:
  existingSecret: gitea-oauthclient-oauthproxy

extraArgs:
  provider: oidc
  provider-display-name: Acend Login
  oidc-issuer-url: https://gitea.training.cluster.acend.ch

ingress:
 enabled: true
 hosts:
   - oauth-proxy.training.cluster.acend.ch
 tls:
 - hosts:
   - oauth-proxy.training.cluster.acend.ch