apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: node-feature-discovery
    releaseName: node-feature-discovery
    namespace: nfd
    version: 0.16.4
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
