apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: node-feature-discovery
    releaseName: node-feature-discovery
    includeCRDs: true
    namespace: nfd
    version: 0.17.2
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    valuesFile: values.yaml
