---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acend-acme
spec:
  acme:
    email: info@acend.ch
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acend-acme-clusterissuer-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.acend.ch
            solverName: hosttech
            config:
              secretName: hosttech-secret
              apiUrl: https://api.ns1.hosttech.eu/api/user/v1
        selector:
          dnsNames:
            - '*.labapp.acend.ch'
