controller:
  kind: Deployment
  replicaCount: 3

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"

  ingressClassResource:
    default: true
    enabled: true

  extraArgs:
    default-ssl-certificate: cert-manager/acend-wildcard

  metrics:
    enabled: true

  serviceMonitor:
    enabled: true

  service:
    type: LoadBalancer