#cloud-config

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh
  - ${cluster_join_command}

mounts:
- [ bpffs, /sys/fs/bpf, bpf, "default", 0, 0 ]

package_update: true
package_upgrade: true