---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitroing-admin-rb
  namespace: {{ .Values.user }}-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.user }}-webshell
  namespace: {{ .Values.user }}