{{ if .Values.createSecrets.userConfig }}
apiVersion: v1
{{ if not .Values.credentials.usePasswordGenerator }}
data:
  username: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
{{ end }}
kind: Secret
metadata:
  labels:
    acend-userconfig: "true"
{{ if .Values.credentials.usePasswordGenerator }}
  annotations:
    secret-generator.v1.mittwald.de/basic-auth-username: {{ .Values.user }}
    secret-generator.v1.mittwald.de/type: basic-auth
    secret-generator.v1.mittwald.de/length: "16"
{{ end }}
  namespace: {{ .Values.user }}
  name: acend-userconfig
type: Opaque
{{ end }}