{{ if .Values.createSecrets.userconfif }}
apiVersion: v1
data:
  username: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
kind: Secret
metadata:
  labels:
    acend-userconfig: "true"
  namespace: {{ .Values.user }}
  name: acend-userconfig
type: Opaque
{{ end }}