{{ if .Values.createSecrets.basicAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webshell-basic-auth
  namespace: {{ .Values.user }}
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.user .Values.password_bcrypt | b64enc | quote }}
{{ end }}